name: Python Package using Conda

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Greetings"
        default: "Hello there!"
        required: true

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Test with pytest
      run: |
        echo ${{ github.event.inputs.name }}
    - id: packageandpush
      uses: sabernetic/python-package-publisher@v1
      with:
        what-to-do: 'Package and Push'
