name: Python Package Test

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Greetings"
        default: "Hello there!"
        required: true

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Test inputs
      run: |
        echo input: ${{ github.event.inputs.name }}
    - id: packageandpush
      uses: sabernetic/python-package-publisher@master
      with:
        what-to-do: ${{ github.event.inputs.name }}
